before_install: cd earl
install: rebar compile && rebar skip_deps=true eunit
script: rebar eunit
after_success: make

language: erlang
otp_release:
        - 17.1
        - 17.0
        - R16B03-1
        - R16B03
        - R16B02
        - R16B01
